### ISSUE TITLE
[Feat] 도메인 설계 & 회원가입 

### ISSUE THREAD

**Issue by dionisos198** [Cre8-graduation-project/Cre8-BackEnd#17]
## 🔥 Issue
ERD 를 바탕으로 도메인을 설계한 이후 회원가입 로직을 작성한다. 

## ✅ TODO
- [x]  ERD 를 바탕으로 도메인 설계
- [x] commit message 편리하게 넣기 (.gitmessage.txt)
- [x] ERD 설계 검증 
- [x] 회원가입 -TDD 설계
- [x] 회원가입 비즈니스 로직 설계
- [x] 회원가입 api 작성
