### ISSUE TITLE
[Refactoring&Setting] 회원가입 로직 수정 및 테스트 , swagger setting 

### ISSUE THREAD

**Issue by dionisos198** [Cre8-graduation-project/Cre8-BackEnd#19]
## 🔥 Issue
회의 내용을 바탕으로 
기존의 이메일을 아이디로 쓰는 것을 따로 구분 하고 ( 따라서 인증번호 구현 필요)
또한 swagger 세팅으로 프론트 개발자가 편하게 작업할 수 있도록 한다.

## ✅ TODO
- [x]  이메일 -> 아이디 + 이메일 로 분리 + 테스트
- [x] 아이디 중복 검증 예외
- [x] 이메일 인증 구현 
- [x]  이메일 검증 예외 
- [x]  swagger 세팅
