### ISSUE TITLE
[Setting] 프로젝트 세팅 

### ISSUE THREAD

**Issue by dionisos198** [Cre8-graduation-project/Cre8-BackEnd#2]
## 🔥 Issue
기본적인 백앤드 프로젝트 세팅을 수행한다. 

## ✅ TODO
- [x]  build.gradle 세팅
- [x] git.ignore 설정
- [x] pull request template 설정
