### ISSUE TITLE
[Feat] 자기 소개 페이지 작성 

### ISSUE THREAD

**Issue by dionisos198** [Cre8-graduation-project/Cre8-BackEnd#27]
## 🔥 Issue
자기 소개 페이지를 작성한다. 

## ✅ TODO
- [x]  유튜브 링크 및 SNS 링크 사이트 입력 
- [x] 자기소개 페이지 작성 
- [x] 자기소개 페이지 html 문서 꾸미는 방법 찾기 
- [x] html 문서 적용 방법 생각 및 코드 적용 
- [x] swagger 적용
- [x] security test code 작성
